// This file is autogenerated. Changes will be overwritten.
#include "VM3RHJVJPW/moc_project_manager.cpp"
#include "VM3RHJVJPW/moc_selection_manager.cpp"
#include "XGR2Y73JXP/moc_command_dispatcher.cpp"
#include "6K46MK4XT7/moc_uuid_generator.cpp"
#include "L7NLU6VBVA/moc_project_persistence.cpp"
#include "VM3IGXGCA7/moc_timeline_manager.cpp"
#include "5TXKQG4ACT/moc_scriptable_timeline.cpp"
