-- Channel names from embedded WAV metadata — 023 Feature B.
--
-- Pro-audio BWF files name each recorded channel in an iXML <TRACK_LIST>
-- (one <TRACK> per channel, <INTERLEAVE_INDEX> = physical channel position
-- 1-based, <NAME> = the mixer's label). A synced master's audio tracks should
-- show those names (BOOM/LAV-A/...) instead of a placeholder.
--
-- Domain expectation (independent of implementation): for the fixture
-- synthetic_4ch_named_ixml_48k.wav the interleaved channels are named, in
-- order, MIX / BOOM / LAV-A / LAV-B. media_refs index channels 0-based
-- (source_channel), so source_channel 0 -> "MIX", 1 -> "BOOM",
-- 2 -> "LAV-A", 3 -> "LAV-B". A file with no iXML names yields nil (blank).
--
-- Run via: ./build/bin/jve --test tests/synthetic/integration/test_channel_names_ixml.lua

local env = require("synthetic.integration.integration_test_env")
local channel_names = require("core.media.channel_names")

print("--- test_channel_names_ixml.lua ---")

local NAMED = env.test_media_path("synthetic_4ch_named_ixml_48k.wav")
-- A plain tone WAV with no iXML TRACK_LIST (generated by the tone fixtures).
local UNNAMED = env.test_media_path("synthetic_8ch_amp_ramp_48k.wav")

local MEDIA_ID = "media-namedwav-001"
local expected = { [0] = "MIX", [1] = "BOOM", [2] = "LAV-A", [3] = "LAV-B" }

for ch = 0, 3 do
    local got = channel_names.get(MEDIA_ID, NAMED, ch)
    assert(got == expected[ch], string.format(
        "source_channel %d: expected %q, got %s",
        ch, expected[ch], tostring(got)))
end
print("  4 channels resolved: MIX / BOOM / LAV-A / LAV-B")

-- Out-of-range channel -> nil (no name, renders blank).
assert(channel_names.get(MEDIA_ID, NAMED, 7) == nil,
    "channel beyond TRACK_LIST must be nil")

-- A file with no iXML TRACK_LIST -> nil for every channel (blank).
local none = channel_names.get("media-unnamed-002", UNNAMED, 0)
assert(none == nil, string.format(
    "file without iXML names must yield nil, got %s", tostring(none)))
print("  unnamed file -> nil (blank)")

print("✅ test_channel_names_ixml.lua passed")
